/**
 * KAZI - Seed Data for Abuja, Nigeria
 * Contains 24+ realistic service providers, categories, initial jobs, reviews, and demo users.
 */

const KAZI_SEED_DATA = {
  cities: [
    { id: 'abuja', name: 'Abuja', state: 'FCT', active: true, areas: ['Wuse II', 'Maitama', 'Garki', 'Jabi', 'Utako', 'Gwarinpa', 'Apo', 'Kubwa', 'Lokogoma', 'Gudu', 'Asokoro'] },
    { id: 'lagos', name: 'Lagos', state: 'Lagos State', active: false, areas: ['Ikeja', 'Lekki', 'Victoria Island', 'Yaba', 'Surulere'] },
    { id: 'portharcourt', name: 'Port Harcourt', state: 'Rivers', active: false, areas: ['GRA Phase 2', 'Old GRA', 'Trans Amadi', 'D-Line'] }
  ],

  categories: [
    { id: 'electrician', name: 'Electrician', icon: 'zap', count: 5, description: 'Wiring, conduit, inverters, solar panels, generators & breakers' },
    { id: 'plumber', name: 'Plumber', icon: 'droplet', count: 5, description: 'Pipes, borehole pumps, bathroom fittings, water heaters & drainage' },
    { id: 'mechanic', name: 'Mechanic', icon: 'tool', count: 5, description: 'Engine diagnosis, brakes, suspension, auto electrical & routine servicing' },
    { id: 'tailor', name: 'Tailor', icon: 'scissors', count: 3, description: 'Native attire, bespoke suits, alterations, embroidery & bridal wear' },
    { id: 'cleaner', name: 'Cleaner', icon: 'sparkles', count: 3, description: 'Post-construction cleaning, residential deep clean & fumigation' },
    { id: 'barber', name: 'Barber', icon: 'user-check', count: 3, description: 'Executive home visits, beard grooming, fading & skin treatment' },
    { id: 'ac-tech', name: 'AC Technician', icon: 'wind', count: 2, description: 'AC servicing, gas refills, compressor fixes & multi-split installations' },
    { id: 'painter', name: 'Painter', icon: 'pen-tool', count: 2, description: 'Interior/exterior screeding, decorative painting & stucco finish' }
  ],

  users: [
    {
      id: 'usr_customer_01',
      name: 'Funke Adeyemi',
      phone: '+234 803 555 0192',
      email: 'funke.adeyemi@kazi.ng',
      city: 'Abuja',
      area: 'Wuse II',
      role: 'customer',
      avatarBg: '#047857',
      initials: 'FA',
      createdAt: '2026-08-10T09:00:00.000Z'
    },
    {
      id: 'usr_provider_01',
      name: 'Chinedu Okafor',
      phone: '+234 802 333 4411',
      email: 'chinedu.electrician@kazi.ng',
      city: 'Abuja',
      area: 'Wuse II',
      role: 'provider',
      providerId: 'prv_001',
      avatarBg: '#1e3a8a',
      initials: 'CO',
      createdAt: '2026-01-12T11:00:00.000Z'
    }
  ],

  providers: [
    // --- 5 ELECTRICIANS ---
    {
      id: 'prv_001',
      userId: 'usr_provider_01',
      name: 'Chinedu Okafor',
      category: 'Electrician',
      city: 'Abuja',
      serviceAreas: ['Wuse II', 'Maitama', 'Garki', 'Jabi', 'Utako'],
      bio: 'Licensed electrical technician with over 9 years of hands-on experience in residential and commercial buildings across Abuja. Specializes in distribution board upgrades, inverter setup, and electrical troubleshooting.',
      phone: '+234 802 333 4411',
      rating: 4.8,
      completedJobs: 47,
      verifiedReviews: 39,
      typicalPriceMin: 25000,
      typicalPriceMax: 40000,
      availability: 'Available Today',
      isVerifiedIdentity: true,
      initials: 'CO',
      avatarBg: '#0f766e',
      services: [
        'Distribution Board Upgrades',
        'Inverter & Solar System Setup',
        'Fault Finding & Circuit Tripping',
        'House Conduit & Surface Wiring',
        'Generator Changeover Installation'
      ],
      createdAt: '2026-01-12T11:00:00.000Z'
    },
    {
      id: 'prv_002',
      userId: 'usr_p02',
      name: 'Tunde Bakare',
      category: 'Electrician',
      city: 'Abuja',
      serviceAreas: ['Garki', 'Apo', 'Gudu', 'Asokoro'],
      bio: 'Expert in load balancing, industrial sockets, and surge protection. Over 7 years servicing homes and offices in Garki and Apo.',
      phone: '+234 803 777 8822',
      rating: 4.7,
      completedJobs: 34,
      verifiedReviews: 28,
      typicalPriceMin: 20000,
      typicalPriceMax: 35000,
      availability: 'Available Tomorrow',
      isVerifiedIdentity: true,
      initials: 'TB',
      avatarBg: '#1d4ed8',
      services: [
        'Surge Protection & Earthing',
        'Lighting & Chandelier Mounting',
        'Appliance Installation',
        'Prepaid Meter Relocation Assistance'
      ],
      createdAt: '2026-02-05T10:00:00.000Z'
    },
    {
      id: 'prv_003',
      userId: 'usr_p03',
      name: 'Ibrahim Musa',
      category: 'Electrician',
      city: 'Abuja',
      serviceAreas: ['Maitama', 'Wuse II', 'Asokoro', 'Guzape'],
      bio: 'Specialist in high-end residential automated lighting, hybrid solar inverters, and emergency electrical diagnostics.',
      phone: '+234 814 666 9911',
      rating: 4.9,
      completedJobs: 52,
      verifiedReviews: 46,
      typicalPriceMin: 30000,
      typicalPriceMax: 55000,
      availability: 'Available Today',
      isVerifiedIdentity: true,
      initials: 'IM',
      avatarBg: '#047857',
      services: [
        'Hybrid Solar Inverter Configuration',
        'Smart Switch & Home Automation',
        'Emergency Power Restoration',
        'Main Switchboard Rewiring'
      ],
      createdAt: '2026-01-08T09:30:00.000Z'
    },
    {
      id: 'prv_004',
      userId: 'usr_p04',
      name: 'Emeka Nwosu',
      category: 'Electrician',
      city: 'Abuja',
      serviceAreas: ['Gwarinpa', 'Jabi', 'Utako', 'Dawaki'],
      bio: 'Quick responder for Gwarinpa and Jabi corridors. Skilled at locating difficult short circuits and repairing damaged conduit lines.',
      phone: '+234 809 222 3344',
      rating: 4.6,
      completedJobs: 29,
      verifiedReviews: 22,
      typicalPriceMin: 18000,
      typicalPriceMax: 32000,
      availability: 'Available Today',
      isVerifiedIdentity: false,
      initials: 'EN',
      avatarBg: '#b45309',
      services: [
        'Short Circuit Repair',
        'Wall Socket & Breaker Replacement',
        'Water Heater Electrical Connects',
        'Security Lighting Installation'
      ],
      createdAt: '2026-03-14T14:00:00.000Z'
    },
    {
      id: 'prv_005',
      userId: 'usr_p05',
      name: 'Sunday Adeleke',
      category: 'Electrician',
      city: 'Abuja',
      serviceAreas: ['Jabi', 'Utako', 'Wuse II', 'Mabushi'],
      bio: 'Known for transparent material pricing and neat conduit finishing. Provides reliable electrical maintenance for apartments.',
      phone: '+234 805 111 7733',
      rating: 4.8,
      completedJobs: 41,
      verifiedReviews: 35,
      typicalPriceMin: 22000,
      typicalPriceMax: 38000,
      availability: 'Available Tomorrow',
      isVerifiedIdentity: true,
      initials: 'SA',
      avatarBg: '#475569',
      services: [
        'Electrical Diagnostics',
        'Inverter Battery Bank Rewiring',
        'Kitchen Appliance Wiring',
        'Conduit Cable Pulling'
      ],
      createdAt: '2026-02-18T16:00:00.000Z'
    },

    // --- 5 PLUMBERS ---
    {
      id: 'prv_006',
      userId: 'usr_p06',
      name: 'Emeka Eze',
      category: 'Plumber',
      city: 'Abuja',
      serviceAreas: ['Garki', 'Wuse II', 'Maitama', 'Asokoro'],
      bio: 'Master plumber with 11 years experience in pressurized water systems, bathroom fixtures, and borehole submersible pumps.',
      phone: '+234 803 888 1234',
      rating: 4.9,
      completedJobs: 58,
      verifiedReviews: 50,
      typicalPriceMin: 15000,
      typicalPriceMax: 30000,
      availability: 'Available Today',
      isVerifiedIdentity: true,
      initials: 'EE',
      avatarBg: '#0284c7',
      services: [
        'Borehole & Pressure Pump Repair',
        'Bathroom Shower & Toilet Upgrades',
        'Concealed Pipe Leak Detection',
        'Water Heater Installation & Descaling',
        'Overhead Tank Cleaning & Float Valves'
      ],
      createdAt: '2026-01-04T12:00:00.000Z'
    },
    {
      id: 'prv_007',
      userId: 'usr_p07',
      name: 'Usman Garba',
      category: 'Plumber',
      city: 'Abuja',
      serviceAreas: ['Utako', 'Jabi', 'Wuse II', 'Mabushi'],
      bio: 'Prompt plumbing professional focusing on emergency leak repair, kitchen sinks, and sewage drainage unclogging.',
      phone: '+234 812 444 5566',
      rating: 4.7,
      completedJobs: 31,
      verifiedReviews: 26,
      typicalPriceMin: 18000,
      typicalPriceMax: 35000,
      availability: 'Available Today',
      isVerifiedIdentity: true,
      initials: 'UG',
      avatarBg: '#0f766e',
      services: [
        'Drainage Unclogging',
        'Sink & Basin Trap Replacement',
        'Burst Pipe Repair',
        'Water Filter Installation'
      ],
      createdAt: '2026-02-20T08:00:00.000Z'
    },
    {
      id: 'prv_008',
      userId: 'usr_p08',
      name: 'Babatunde Alabi',
      category: 'Plumber',
      city: 'Abuja',
      serviceAreas: ['Wuse II', 'Maitama', 'Garki', 'Central Area'],
      bio: 'Specialist in PPR piping, sanitary ware installations, and high-efficiency water management for modern residential estates.',
      phone: '+234 807 999 3322',
      rating: 4.8,
      completedJobs: 44,
      verifiedReviews: 37,
      typicalPriceMin: 20000,
      typicalPriceMax: 40000,
      availability: 'Available Tomorrow',
      isVerifiedIdentity: true,
      initials: 'BA',
      avatarBg: '#2563eb',
      services: [
        'PPR Piping Installation',
        'Luxury Sanitary Fixture Setup',
        'Water Pressure Booster Calibration',
        'Pipe Thermal Insulation'
      ],
      createdAt: '2026-01-19T13:00:00.000Z'
    },
    {
      id: 'prv_009',
      userId: 'usr_p09',
      name: 'Jude Okeke',
      category: 'Plumber',
      city: 'Abuja',
      serviceAreas: ['Apo', 'Gudu', 'Lokogoma', 'Lugbe'],
      bio: 'Reliable plumber based in Apo. Fast response times for broken stopcocks, floating valves, and soakaway line maintenance.',
      phone: '+234 816 333 8844',
      rating: 4.6,
      completedJobs: 27,
      verifiedReviews: 21,
      typicalPriceMin: 15000,
      typicalPriceMax: 28000,
      availability: 'Available Today',
      isVerifiedIdentity: false,
      initials: 'JO',
      avatarBg: '#64748b',
      services: [
        'Stopcock & Valve Replacement',
        'Toilet Cistern Flush Kit Repair',
        'PVC Pipe Fitting',
        'Outdoor Tap Installation'
      ],
      createdAt: '2026-03-02T10:00:00.000Z'
    },
    {
      id: 'prv_010',
      userId: 'usr_p10',
      name: 'Mohammed Bello',
      category: 'Plumber',
      city: 'Abuja',
      serviceAreas: ['Kubwa', 'Gwarinpa', 'Dawaki', 'Dei-Dei'],
      bio: 'Serving the Kubwa and Gwarinpa axis with honest pricing and solid workmanship on domestic water lines and tank connections.',
      phone: '+234 809 777 6655',
      rating: 4.7,
      completedJobs: 36,
      verifiedReviews: 30,
      typicalPriceMin: 12000,
      typicalPriceMax: 25000,
      availability: 'Available Today',
      isVerifiedIdentity: true,
      initials: 'MB',
      avatarBg: '#059669',
      services: [
        'Domestic Pipe Repairs',
        'Water Storage Tank Interconnection',
        'Kitchen Plumbing',
        'Drain Trap Maintenance'
      ],
      createdAt: '2026-02-12T15:00:00.000Z'
    },

    // --- 5 MECHANICS ---
    {
      id: 'prv_011',
      userId: 'usr_p11',
      name: 'Kelechi Amadi',
      category: 'Mechanic',
      city: 'Abuja',
      serviceAreas: ['Apo', 'Garki', 'Gudu', 'Wuse II'],
      bio: 'Certified master mechanic at Apo Mechanic Village. 14 years specializing in Japanese and German vehicles, computerized scanning, and transmission overhaul.',
      phone: '+234 803 111 9988',
      rating: 4.8,
      completedJobs: 62,
      verifiedReviews: 54,
      typicalPriceMin: 25000,
      typicalPriceMax: 60000,
      availability: 'Available Today',
      isVerifiedIdentity: true,
      initials: 'KA',
      avatarBg: '#b91c1c',
      services: [
        'Computerized Engine Diagnostics (OBD2)',
        'Brake Rotor & Pad Replacement',
        'Suspension Bushing & Shock Absorbers',
        'Transmission Fluid Flush & Service',
        'Engine Overheating Investigation'
      ],
      createdAt: '2026-01-02T09:00:00.000Z'
    },
    {
      id: 'prv_012',
      userId: 'usr_p12',
      name: 'Yakubu Danladi',
      category: 'Mechanic',
      city: 'Abuja',
      serviceAreas: ['Utako', 'Jabi', 'Wuse II', 'Mabushi'],
      bio: 'Utako-based auto specialist. Transparent on genuine parts sourcing with clear diagnostic reports before any bolt is turned.',
      phone: '+234 813 555 4433',
      rating: 4.7,
      completedJobs: 39,
      verifiedReviews: 33,
      typicalPriceMin: 20000,
      typicalPriceMax: 50000,
      availability: 'Available Tomorrow',
      isVerifiedIdentity: true,
      initials: 'YD',
      avatarBg: '#c2410c',
      services: [
        'Routine Engine Tune-up & Filters',
        'Alternator & Starter Motor Fixes',
        'Steering Rack Maintenance',
        'Fuel Pump Replacement'
      ],
      createdAt: '2026-02-01T11:00:00.000Z'
    },
    {
      id: 'prv_013',
      userId: 'usr_p13',
      name: 'Rasheed Sanusi',
      category: 'Mechanic',
      city: 'Abuja',
      serviceAreas: ['Gudu', 'Apo', 'Garki', 'Asokoro'],
      bio: 'Expert auto-electrician and mechanical troubleshooter. Known for resolving stubborn check-engine codes and wiring faults.',
      phone: '+234 802 666 7788',
      rating: 4.9,
      completedJobs: 48,
      verifiedReviews: 42,
      typicalPriceMin: 25000,
      typicalPriceMax: 55000,
      availability: 'Available Today',
      isVerifiedIdentity: true,
      initials: 'RS',
      avatarBg: '#334155',
      services: [
        'Auto Electrical Troubleshooting',
        'ECU & Sensor Replacement',
        'Battery Drain Investigation',
        'Cooling Fan & Radiator Repair'
      ],
      createdAt: '2026-01-25T14:30:00.000Z'
    },
    {
      id: 'prv_014',
      userId: 'usr_p14',
      name: 'Kenneth Obi',
      category: 'Mechanic',
      city: 'Abuja',
      serviceAreas: ['Jabi', 'Maitama', 'Wuse II', 'Utako'],
      bio: 'Mobile mechanic providing roadside assistance, pre-purchase vehicle inspections, and on-site routine servicing.',
      phone: '+234 817 222 1199',
      rating: 4.6,
      completedJobs: 30,
      verifiedReviews: 24,
      typicalPriceMin: 18000,
      typicalPriceMax: 45000,
      availability: 'Available Today',
      isVerifiedIdentity: false,
      initials: 'KO',
      avatarBg: '#4d7c0f',
      services: [
        'Pre-Purchase Vehicle Inspection',
        'Mobile Oil & Filter Change',
        'Emergency Jumpstarts & Belt Swaps',
        'Brake Caliper Servicing'
      ],
      createdAt: '2026-03-08T10:00:00.000Z'
    },
    {
      id: 'prv_015',
      userId: 'usr_p15',
      name: 'Samuel Olatunji',
      category: 'Mechanic',
      city: 'Abuja',
      serviceAreas: ['Gwarinpa', 'Dawaki', 'Kubwa', 'Jabi'],
      bio: 'Trusted workshop in Gwarinpa. Clean workshop practices with fixed quotes and upfront diagnosis on suspension and drive shafts.',
      phone: '+234 808 333 7711',
      rating: 4.7,
      completedJobs: 35,
      verifiedReviews: 29,
      typicalPriceMin: 20000,
      typicalPriceMax: 48000,
      availability: 'Available Tomorrow',
      isVerifiedIdentity: true,
      initials: 'SO',
      avatarBg: '#7c2d12',
      services: [
        'Wheel Bearing & Hub Replacement',
        'Drive Shaft & CV Joint Repair',
        'Timing Belt & Water Pump',
        'Clutch Plate Replacement'
      ],
      createdAt: '2026-02-14T12:00:00.000Z'
    },

    // --- 3 TAILORS ---
    {
      id: 'prv_016',
      userId: 'usr_p16',
      name: 'Amina Bello',
      category: 'Tailor',
      city: 'Abuja',
      serviceAreas: ['Wuse II', 'Maitama', 'Garki', 'Asokoro'],
      bio: 'Renowned fashion designer and bespoke tailor in Wuse II. Renowned for impeccable Agbada, Senator wear, and formal bespoke embroidery with guaranteed delivery dates.',
      phone: '+234 803 999 4433',
      rating: 4.9,
      completedJobs: 56,
      verifiedReviews: 49,
      typicalPriceMin: 15000,
      typicalPriceMax: 45000,
      availability: 'Available Today',
      isVerifiedIdentity: true,
      initials: 'AB',
      avatarBg: '#be185d',
      services: [
        'Men’s Bespoke Senator & Kaftan',
        'Luxury Agbada & Monogramming',
        'Ladies Native & Corporate Wear',
        'Express Measurements & Alterations'
      ],
      createdAt: '2026-01-15T10:00:00.000Z'
    },
    {
      id: 'prv_017',
      userId: 'usr_p17',
      name: 'Hadiza Yusuf',
      category: 'Tailor',
      city: 'Abuja',
      serviceAreas: ['Maitama', 'Asokoro', 'Wuse II', 'Guzape'],
      bio: 'Specialist in Northern Nigerian traditional couture, high-end bridal dresses, and precise fitting. Never compromises on delivery dates.',
      phone: '+234 814 888 2211',
      rating: 4.8,
      completedJobs: 43,
      verifiedReviews: 38,
      typicalPriceMin: 20000,
      typicalPriceMax: 60000,
      availability: 'Available Tomorrow',
      isVerifiedIdentity: true,
      initials: 'HY',
      avatarBg: '#9333ea',
      services: [
        'Bridal & Aso-Ebi Stitching',
        'Lace & Silk Gowns',
        'Traditional Caps & Embroidery',
        'Wardrobe Fitting'
      ],
      createdAt: '2026-02-10T11:00:00.000Z'
    },
    {
      id: 'prv_018',
      userId: 'usr_p18',
      name: 'Blessing Okon',
      category: 'Tailor',
      city: 'Abuja',
      serviceAreas: ['Garki', 'Apo', 'Gudu', 'Jabi'],
      bio: 'Affordable, crisp tailoring for everyday workwear, school uniforms, and quick garment alterations in Garki.',
      phone: '+234 802 111 6655',
      rating: 4.7,
      completedJobs: 32,
      verifiedReviews: 27,
      typicalPriceMin: 12000,
      typicalPriceMax: 35000,
      availability: 'Available Today',
      isVerifiedIdentity: true,
      initials: 'BO',
      avatarBg: '#b91c1c',
      services: [
        'Trousers & Jacket Resizing',
        'Corporate Shirts & Skirts',
        'Zipper & Hemming Corrections',
        'Casual Ankara Outfits'
      ],
      createdAt: '2026-02-28T09:00:00.000Z'
    },

    // --- 3 CLEANERS ---
    {
      id: 'prv_019',
      userId: 'usr_p19',
      name: 'Fatima Mohammed',
      category: 'Cleaner',
      city: 'Abuja',
      serviceAreas: ['Jabi', 'Utako', 'Wuse II', 'Maitama'],
      bio: 'Leads an energetic, vetted cleaning team in Jabi. Specialized in post-tenancy deep cleans, upholstery shampooing, and fumigation.',
      phone: '+234 816 777 3344',
      rating: 4.8,
      completedJobs: 49,
      verifiedReviews: 42,
      typicalPriceMin: 15000,
      typicalPriceMax: 35000,
      availability: 'Available Today',
      isVerifiedIdentity: true,
      initials: 'FM',
      avatarBg: '#0e7490',
      services: [
        'Full Apartment Deep Cleaning',
        'Sofa & Rug Steam Extraction',
        'Kitchen Grease & Oven Scrub',
        'Eco-friendly Pest Fumigation'
      ],
      createdAt: '2026-01-20T13:00:00.000Z'
    },
    {
      id: 'prv_020',
      userId: 'usr_p20',
      name: 'Ngozi Eze',
      category: 'Cleaner',
      city: 'Abuja',
      serviceAreas: ['Gwarinpa', 'Dawaki', 'Jabi', 'Kubwa'],
      bio: 'Punctual, thorough, and trustworthy. Over 5 years keeping homes spotless across Gwarinpa estates with industrial equipment.',
      phone: '+234 803 444 8822',
      rating: 4.9,
      completedJobs: 64,
      verifiedReviews: 57,
      typicalPriceMin: 18000,
      typicalPriceMax: 40000,
      availability: 'Available Today',
      isVerifiedIdentity: true,
      initials: 'NE',
      avatarBg: '#059669',
      services: [
        'Post-Construction Renovation Cleaning',
        'Window & Glass Polishing',
        'Tile Grout Descaling',
        'Routine Weekly Home Clean'
      ],
      createdAt: '2026-01-05T08:30:00.000Z'
    },
    {
      id: 'prv_021',
      userId: 'usr_p21',
      name: 'Grace Danjuma',
      category: 'Cleaner',
      city: 'Abuja',
      serviceAreas: ['Wuse II', 'Maitama', 'Asokoro', 'Garki'],
      bio: 'Executive cleaning specialist for modern apartments and corporate offices. Exceptional attention to detail and discreet service.',
      phone: '+234 809 111 4455',
      rating: 4.7,
      completedJobs: 38,
      verifiedReviews: 31,
      typicalPriceMin: 20000,
      typicalPriceMax: 45000,
      availability: 'Available Tomorrow',
      isVerifiedIdentity: true,
      initials: 'GD',
      avatarBg: '#4338ca',
      services: [
        'Office Sanitization & Cleaning',
        'Marble Floor Buffing',
        'Curtain & Mattress Sanitization',
        'Bathroom Odor Elimination'
      ],
      createdAt: '2026-02-15T15:00:00.000Z'
    },

    // --- 3 BARBERS ---
    {
      id: 'prv_022',
      userId: 'usr_p22',
      name: 'Tayo Adeyemi',
      category: 'Barber',
      city: 'Abuja',
      serviceAreas: ['Wuse II', 'Maitama', 'Jabi', 'Garki'],
      bio: 'Master barber providing VIP mobile grooming in Wuse II and Maitama. Sanitized wireless clippers, hot towel treatment, and sharp skin fades.',
      phone: '+234 802 888 7766',
      rating: 4.9,
      completedJobs: 71,
      verifiedReviews: 65,
      typicalPriceMin: 5000,
      typicalPriceMax: 15000,
      availability: 'Available Today',
      isVerifiedIdentity: true,
      initials: 'TA',
      avatarBg: '#ea580c',
      services: [
        'VIP Home Visit Haircut & Shave',
        'Skin Fade & Sharp Line-up',
        'Beard Sculpting & Hot Towel Oil',
        'Kids Gentle Haircut'
      ],
      createdAt: '2026-01-10T12:00:00.000Z'
    },
    {
      id: 'prv_023',
      userId: 'usr_p23',
      name: 'Collins Igwe',
      category: 'Barber',
      city: 'Abuja',
      serviceAreas: ['Gwarinpa', 'Jabi', 'Utako', 'Dawaki'],
      bio: 'Gwarinpa based barber with 8 years experience. Famous for crisp beard fades and zero razor bumps treatment.',
      phone: '+234 816 222 5599',
      rating: 4.8,
      completedJobs: 53,
      verifiedReviews: 46,
      typicalPriceMin: 4000,
      typicalPriceMax: 12000,
      availability: 'Available Today',
      isVerifiedIdentity: true,
      initials: 'CI',
      avatarBg: '#b45309',
      services: [
        'Modern Haircut & Razor Finish',
        'Anti-Bump Facial Treatment',
        'Hair Dye & Texturizing',
        'Home & Office Grooming Call'
      ],
      createdAt: '2026-02-08T14:00:00.000Z'
    },
    {
      id: 'prv_024',
      userId: 'usr_p24',
      name: 'Ahmed Sani',
      category: 'Barber',
      city: 'Abuja',
      serviceAreas: ['Maitama', 'Asokoro', 'Wuse II', 'Central Area'],
      bio: 'Executive groomer servicing diplomats and professionals in Maitama. Punctual, courteous, and brings a complete luxury salon kit to your doorstep.',
      phone: '+234 803 666 1122',
      rating: 4.9,
      completedJobs: 60,
      verifiedReviews: 52,
      typicalPriceMin: 6000,
      typicalPriceMax: 18000,
      availability: 'Available Tomorrow',
      isVerifiedIdentity: true,
      initials: 'AS',
      avatarBg: '#047857',
      services: [
        'Executive Shave & Facial Scrub',
        'Precision Scissor Haircut',
        'Beard Conditioning & Edge Alignment',
        'Wedding Groom Party Service'
      ],
      createdAt: '2026-01-18T16:00:00.000Z'
    }
  ],

  jobs: [
    // Pre-populated active job matching the spec:
    {
      id: 'job_001',
      customerId: 'usr_customer_01',
      customerName: 'Funke Adeyemi',
      providerId: 'prv_001',
      providerName: 'Chinedu Okafor',
      category: 'Electrician',
      serviceName: 'Distribution Board Upgrades',
      description: 'Breaker board tripping frequently whenever generator switch is flipped. Inspect main conduit connection and install 63A surge isolator.',
      agreedPrice: 32000,
      agreedDate: '2026-10-04',
      status: 'in-progress',
      notes: 'Customer lives in Wuse II near Banex plaza. Security gate pass will be texted.',
      issue: null,
      createdAt: '2026-10-01T10:15:00.000Z',
      completedAt: null
    },
    // Pre-populated completed job:
    {
      id: 'job_002',
      customerId: 'usr_customer_01',
      customerName: 'Funke Adeyemi',
      providerId: 'prv_006',
      providerName: 'Emeka Eze',
      category: 'Plumber',
      serviceName: 'Borehole & Pressure Pump Repair',
      description: 'Submersible water pump was making grinding sound and stopping every 10 minutes. Cleaned foot valve and replaced pressure capacitor.',
      agreedPrice: 18000,
      agreedDate: '2026-09-28',
      status: 'completed',
      notes: 'Punctual arrival. Finished within 2 hours.',
      issue: null,
      createdAt: '2026-09-27T08:00:00.000Z',
      completedAt: '2026-09-28T16:30:00.000Z'
    },
    // Pre-populated issue reported job:
    {
      id: 'job_003',
      customerId: 'usr_customer_01',
      customerName: 'Funke Adeyemi',
      providerId: 'prv_007',
      providerName: 'Usman Garba',
      category: 'Plumber',
      serviceName: 'Concealed Pipe Leak Detection',
      description: 'Leak inside guest bathroom wall causing dampness. Required leak detection and pipe sealing.',
      agreedPrice: 45000,
      agreedDate: '2026-09-20',
      status: 'issue-reported',
      notes: 'Initial agreement was ₦45,000 all-inclusive.',
      issue: {
        type: 'Price Changed on Site',
        reportedAt: '2026-09-20T15:45:00.000Z',
        reportedBy: 'Funke Adeyemi',
        customerNote: 'Artisan broke the tiles and then demanded an additional ₦25,000 for materials before continuing work, despite our initial agreement of ₦45,000.'
      },
      createdAt: '2026-09-19T14:00:00.000Z',
      completedAt: null
    }
  ],

  reviews: [
    // Reviews for Chinedu Okafor (prv_001)
    {
      id: 'rev_001',
      jobId: 'job_hist_01',
      customerId: 'usr_c02',
      customerName: 'Dr. Aliyu Mohammed',
      providerId: 'prv_001',
      rating: 5,
      reviewText: 'Chinedu came to my residence in Maitama. Diagnosed the inverter fault in 20 minutes. He stuck to the agreed price without demanding any extra fees. Highly recommended!',
      arrivedAsAgreed: true,
      priceAsAgreed: true,
      jobCompleted: true,
      createdAt: '2026-09-24T18:00:00.000Z',
      verified: true
    },
    {
      id: 'rev_002',
      jobId: 'job_hist_02',
      customerId: 'usr_c03',
      customerName: 'Kemi Balogun',
      providerId: 'prv_001',
      rating: 5,
      reviewText: 'Fixed our office distribution board in Wuse II after two other electricians failed. Very professional demeanor and came with his complete toolkit.',
      arrivedAsAgreed: true,
      priceAsAgreed: true,
      jobCompleted: true,
      createdAt: '2026-09-15T12:30:00.000Z',
      verified: true
    },
    {
      id: 'rev_003',
      jobId: 'job_hist_03',
      customerId: 'usr_c04',
      customerName: 'Emeka Nwachukwu',
      providerId: 'prv_001',
      rating: 4,
      reviewText: 'Good work on the changeover switch. Arrived about 25 minutes past the agreed time due to traffic around Berger roundabout, but communicated proactively and did solid work.',
      arrivedAsAgreed: false,
      priceAsAgreed: true,
      jobCompleted: true,
      createdAt: '2026-08-30T17:15:00.000Z',
      verified: true
    },
    // Review for Emeka Eze (job_002)
    {
      id: 'rev_004',
      jobId: 'job_002',
      customerId: 'usr_customer_01',
      customerName: 'Funke Adeyemi',
      providerId: 'prv_006',
      rating: 5,
      reviewText: 'Emeka arrived right on schedule at 10 AM. He brought all the necessary pipe fittings and sorted out our borehole pump cleanly. The agreed ₦18,000 price was strictly respected.',
      arrivedAsAgreed: true,
      priceAsAgreed: true,
      jobCompleted: true,
      createdAt: '2026-09-28T17:00:00.000Z',
      verified: true
    },
    // Review for Kelechi Amadi (prv_011)
    {
      id: 'rev_005',
      jobId: 'job_hist_04',
      customerId: 'usr_c05',
      customerName: 'Sadiq Abubakar',
      providerId: 'prv_011',
      rating: 5,
      reviewText: 'Kelechi scanned my Toyota Prado and located a faulty wheel speed sensor that was triggering the ABS warning. Transparent quote, genuine part, zero guesswork.',
      arrivedAsAgreed: true,
      priceAsAgreed: true,
      jobCompleted: true,
      createdAt: '2026-09-12T16:00:00.000Z',
      verified: true
    },
    // Review for Amina Bello (prv_016)
    {
      id: 'rev_006',
      jobId: 'job_hist_05',
      customerId: 'usr_c06',
      customerName: 'Zainab Okoye',
      providerId: 'prv_016',
      rating: 5,
      reviewText: 'Amina delivered my bespoke Senator outfit 2 days ahead of my brother’s traditional wedding. Flawless stitching and premium finishing. She is now my permanent tailor.',
      arrivedAsAgreed: true,
      priceAsAgreed: true,
      jobCompleted: true,
      createdAt: '2026-09-22T14:00:00.000Z',
      verified: true
    }
  ]
};
